# Generated by Django 5.0.1 on 2025-12-16 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048, verbose_name="분석 URL")),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                ("content", models.TextField(verbose_name="본문 요약")),
                (
                    "is_clickbait",
                    models.BooleanField(default=False, verbose_name="클릭베이트 여부"),
                ),
                (
                    "is_hate_speech",
                    models.BooleanField(default=False, verbose_name="혐오 표현 포함 여부"),
                ),
                (
                    "is_misinformation",
                    models.BooleanField(default=False, verbose_name="허위정보 가능성"),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="전체 신뢰도 (0.0~1.0)"),
                ),
                (
                    "analysis_details",
                    models.JSONField(blank=True, default=dict, verbose_name="상세 분석 결과"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL 분석 결과",
                "verbose_name_plural": "URL 분석 결과들",
                "db_table": "analysis_results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="analysis_re_created_5b0919_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analysis_re_user_id_983605_idx",
                    ),
                    models.Index(fields=["url"], name="analysis_re_url_5f94e9_idx"),
                ],
            },
        ),
    ]
