# Generated by Django 5.0.1 on 2025-12-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="explanation",
            field=models.TextField(
                blank=True, default="", verbose_name="AI 판단 근거 (한 줄 요약)"
            ),
        ),
    ]
