# Generated by Django 5.0.1 on 2025-12-18 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0002_analysisresult_explanation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=2048, verbose_name="분석된 URL"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("educational", "교육적 맥락"),
                            ("citation", "인용/보도"),
                            ("context_misunderstanding", "문맥 오해"),
                        ],
                        max_length=50,
                        verbose_name="오탐 사유",
                    ),
                ),
                (
                    "analysis_result",
                    models.JSONField(default=dict, verbose_name="분석 결과"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="피드백 제출자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 피드백",
                "verbose_name_plural": "사용자 피드백들",
                "db_table": "user_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(fields=["-created_at"], name="user_feedba_created_b8e8c0_idx"),
        ),
        migrations.AddIndex(
            model_name="userfeedback",
            index=models.Index(fields=["reason"], name="user_feedba_reason_5a9e0e_idx"),
        ),
    ]
