# Generated by Django 5.0.1 on 2025-12-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimilarityCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_text",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="쿼리 텍스트"
                    ),
                ),
                (
                    "query_hash",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="쿼리 해시"
                    ),
                ),
                ("results", models.JSONField(verbose_name="검색 결과")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("hit_count", models.IntegerField(default=0, verbose_name="히트 횟수")),
            ],
            options={
                "verbose_name": "유사도 캐시",
                "verbose_name_plural": "유사도 캐시들",
                "db_table": "similarity_cache",
                "ordering": ["-hit_count"],
            },
        ),
        migrations.CreateModel(
            name="NewsDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news_id",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="뉴스 ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(db_index=True, max_length=50, verbose_name="카테고리"),
                ),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=50, verbose_name="하위 카테고리"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=500, verbose_name="부제목"),
                ),
                ("content", models.TextField(verbose_name="본문")),
                (
                    "is_clickbait",
                    models.BooleanField(db_index=True, verbose_name="클릭베이트 여부"),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[("A", "Auto"), ("D", "Direct")],
                        max_length=10,
                        verbose_name="수집 방식",
                    ),
                ),
                (
                    "process_pattern",
                    models.CharField(max_length=10, verbose_name="처리 패턴"),
                ),
                (
                    "process_level",
                    models.CharField(max_length=10, verbose_name="처리 레벨"),
                ),
                ("sentence_count", models.IntegerField(verbose_name="문장 수")),
                ("sentences", models.JSONField(default=list, verbose_name="문장 정보")),
                (
                    "part_num",
                    models.CharField(default="P1", max_length=10, verbose_name="파트 번호"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "뉴스 문서",
                "verbose_name_plural": "뉴스 문서들",
                "db_table": "news_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_clickbait"],
                        name="news_docume_categor_489c35_idx",
                    ),
                    models.Index(
                        fields=["process_type"], name="news_docume_process_aab8c0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector", models.JSONField(verbose_name="임베딩 벡터")),
                (
                    "model_name",
                    models.CharField(
                        default="models/embedding-001",
                        max_length=100,
                        verbose_name="모델명",
                    ),
                ),
                ("dimension", models.IntegerField(default=768, verbose_name="차원 수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="rag.newsdocument",
                        verbose_name="문서",
                    ),
                ),
            ],
            options={
                "verbose_name": "문서 임베딩",
                "verbose_name_plural": "문서 임베딩들",
                "db_table": "document_embeddings",
            },
        ),
    ]
